### ISSUE TITLE
Assets.car is not created

### ISSUE THREAD

**Issue by Marcophono2** [distriqt/AIR-ImageScripts#7]
Hi Michael!

I installed the requierements (brew, imagemagick) on my M1 Mac-mini and let the shell script run. All worked, all icons were created but not the Assets.car. Any idea what went wrong?

Best regards
Marc

```
marcwaesche@Mini-von-Marc assmaker % ./generate.sh 1024.png 2732.png "#ff0000"                                    

USING:

  icon=1024.png

  launch=2732.png

Downloading assets

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                                 Dload  Upload   Total   Spent    Left  Speed

100   141  100   141    0     0    350      0 --:--:-- --:--:-- --:--:--   354

100   152  100   152    0     0    263      0 --:--:-- --:--:-- --:--:--   263

100 82640  100 82640    0     0  13970      0  0:00:05  0:00:05 --:--:-- 20220

Archive:  .tmp.generate-assets.zip

   creating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/

   creating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/LaunchImage.imageset/

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/LaunchImage.imageset/Contents.json

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/LaunchImage.imageset/LaunchImage.png

   creating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/ItunesArtwork@2x.png

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Contents.json

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png

extracting: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/Assets.xcassets/Contents.json

   creating: /Users/marcwaesche/Desktop/assmaker/assets/LaunchScreen.storyboardc/

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/LaunchScreen.storyboardc/01J-lp-oVM-view-Ze5-6b-2t3.nib

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/LaunchScreen.storyboardc/UIViewController-01J-lp-oVM.nib

  inflating: /Users/marcwaesche/Desktop/assmaker/assets/LaunchScreen.storyboardc/Info.plist

Generating icons

Generating Default pngs

Generating Assets.car

- Assets.car: Icons

- Assets.car: Icons created

- Assets.car: actool

- Assets.car: actool complete

cp: /Users/marcwaesche/Desktop/assmaker/tmp/Assets.car: No such file or directory

========== COMPLETE ==============
```
